eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 30001
spring:
  application:
    name: ly-web-manager-cms
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.101.129.54:3306/zhaopin?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
  main:
    allow-bean-definition-overriding: true
feign:
  httpclient:
    enabled: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1


FILE_SERVER_URL: http://192.168.11.128/



