eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 30001
spring:
  application:
    name: ly-web-manager-cms
  main:
    allow-bean-definition-overriding: true
feign:
  httpclient:
    enabled: true
ribbon:
  ReadTimeout: 61000
  ConnectTimeout: 61000

FILE_SERVER_URL: http://192.168.11.128/
